export const LATEST_NEWS_REQUEST = "LATEST_NEWS_REQUEST";
export const LOAD_LATEST_NEWS_SUCCESS = "LOAD_LATEST_NEWS_SUCCESS";

const actions = { LATEST_NEWS_REQUEST, LOAD_LATEST_NEWS_SUCCESS };

export default actions;
