export const LATEST_STORIES_REQUEST = "LATEST_STORIES_REQUEST";
export const LOAD_LATEST_STORIES_SUCCESS = "LOAD_LATEST_STORIES_SUCCESS";

const actions = { LATEST_STORIES_REQUEST, LOAD_LATEST_STORIES_SUCCESS };

export default actions;
