export const LATEST_STORIES_REQUEST = "LATEST_STORIES_REQUEST";
export const LOAD_LATEST_STORIES_SUCCESS = "LOAD_LATEST_STORIES_SUCCESS";
export const LOAD_IN_PICTURES_REQUEST = "LOAD_IN_PICTURES_REQUEST";
export const LOAD_IN_PICTURES_SUCCESS = "LOAD_IN_PICTURES_SUCCESS";
export const LOAD_ECONOMY_NEWS_REQUEST = "LOAD_ECONOMY_NEWS_REQUEST";
export const LOAD_ECONOMY_NEWS_SUCCESS = "LOAD_ECONOMY_NEWS_SUCCESS";
export const LOAD_HEALTH_NEWS_REQUEST = "LOAD_HEALTH_NEWS_REQUEST";
export const LOAD_HEALTH_NEWS_SUCCESS = "LOAD_HEALTH_NEWS_SUCCESS";
export const LOAD_CULTURE_NEWS_REQUEST = "LOAD_CULTURE_NEWS_REQUEST";
export const LOAD_CULTURE_NEWS_SUCCESS = "LOAD_CULTURE_NEWS_SUCCESS";
export const ALL_CULTURE_ARTICLES = "ALL_CULTURE_ARTICLES";

const actions = {
  LATEST_STORIES_REQUEST,
  LOAD_LATEST_STORIES_SUCCESS,
  LOAD_IN_PICTURES_REQUEST,
  LOAD_IN_PICTURES_SUCCESS,
  LOAD_ECONOMY_NEWS_REQUEST,
  LOAD_ECONOMY_NEWS_SUCCESS,
  LOAD_HEALTH_NEWS_REQUEST,
  LOAD_HEALTH_NEWS_SUCCESS,
  LOAD_CULTURE_NEWS_REQUEST,
  LOAD_CULTURE_NEWS_SUCCESS,
  ALL_CULTURE_ARTICLES
};

export default actions;
